name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Run ktlint
      run: ./gradlew spotlessCheck

    - name: Run compileDebugKotlin
      run: ./gradlew compileDebugKotlin

    - name: Run Tests
      run: ./gradlew test

    - name: Run Lint
      run: ./gradlew lint

    - name: Build Project (Debug)
      run: ./gradlew assembleDebug

    - name: Build Project (Release)
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
